### ISSUE TITLE
Hola pa

### ISSUE THREAD

**Issue by gianpieryup** [SantiagoIvan/santiagoivan.github.io#1]
Te recomiendo para mostrar eso en un dominio usar el que te da git por defecto

https://pages.github.com/

Básicamente creas un repo con un nombre en especifico el cual seria tu dominio
De ahi puedes usar esa ruta para poner cada vista que quieras

Yo lo hice asi

https://github.com/gianpieryup/gianpieryup.github.io

Te tiraria un pull request en el readme pero no se y no se me antoja XD

Inclusive lo usan tadp
https://tadp-utn-frba.github.io/
fijate que usan el dominio que te regala git

**Comment by SantiagoIvan** [comment]
MESSI, ahi lo hice, gracias pa
